version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123DagMaluah
      POSTGRES_DB: st-spark-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kafka-net

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: 'form.sync:1:1,form.delete:1:1,response.sync:1:1,form.sync.reply:1:1,form.delete.reply:1:1,response.sync.reply:1:1'
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:

networks:
  kafka-net:
    driver: bridge
